config/routes.rb
require 'resque/server'
Rails.application.routes.draw do

  root 'home#index'
  get 'logout' => 'home#logout'

  get 'about' => 'home#about'
  get 'announcement' => 'home#announcement'
  get 'changelog' => 'home#changelog'

  resources :players, only: [:show] do
    collection do
      get 'search'
    end
    resources :bosses, only: [] do
      get '/:difficulty' => 'bosses#show', as: :show
      get '/:difficulty/batch_parse' => 'bosses#batch_parse', as: :batch_parse
    end
  end

  resources :guilds, only: [:show] do
    get 'reload'
    collection do
      get 'search'
    end
  end

  resources :reports, only: [:show] do
    get 'status', :defaults => {:format => 'js'}
    get 'reload' => 'reports#reload', as: :reload, :defaults => {:format => 'js'}
    get 'batch/:player_id/' => 'reports#batch', as: :batch
    get 'load_fights/:player_id' => 'reports#load_fights', as: :load_fights, :defaults => { :format => 'js' }
    get 'fight_status/' => 'reports#fight_status', as: :fight_status, :defaults => { :format => 'js' }
    get '/:player_id' => 'reports#show_player', as: :player
    get '/:player_id/:fight_id' => 'fight_parses#show', as: :fight_parse
    get '/:player_id/:fight_id/changelog' => 'fight_parses#changelog', as: :changelog
    get '/:player_id/:fight_id/compare' => 'fight_parses#compare', as: :fp_compare
    get '/:fight_id/:player_id/load_hp_graph' => 'fight_parses#load_hp_graph', as: :load_hp_graph
    get '/:fight_id/:player_id/load_class_graph' => 'fight_parses#load_class_graph', as: :load_class_graph
    get '/:fight_id/:player_id/load_casts_table' => 'fight_parses#load_casts_table', as: :load_casts_table
    get '/:fight_id/:player_id/single_parse' => 'fight_parses#single_parse', as: :single_parse
    get '/:fight_id/:player_id/status' => 'fight_parses#status', as: :fp_status, :defaults => { :format => 'js' }
  end

  resources :zones, only: [:index] do
    collection do 
      get 'refresh'
    end
  end

  if Rails.env.development?
    mount Resque::Server.new, at: "/resque"
  end

  match '*path', via: :all, to: 'home#error_404'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params.has_key?(:report_id)
      if (/\// =~ params[:report_id]).nil?
        report_id = params[:report_id].strip
        if report_id == ''
          flash[:danger] = "Please enter a report ID"
          redirect_to root_path and return 
        end
      else
        match = /\/reports\/(\w+)/.match(params[:report_id])
        if match.nil?
          flash[:danger] = "Invalid report ID"
          redirect_to root_path
          return
        else
          report_id = match[1]
        end
      end
      redirect_to report_path(report_id)
    else
      @changelogs = Changelog.order(id: :desc).limit(10).to_a
    end
  end

  def about
    
  end

  def changelog
    @spec = params[:spec]
    @changelogs = Changelog.where(fp_type: @spec).order(id: :desc).to_a
  end

  def logout
    redirect_to root_path
  end

  def error_404
    render file: "#{Rails.root}/public/404.html", status: 404
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<div class="container" style="margin-top: 50px">
  <h3>What does this site do?</h3>
  <p>This site is made for World of Warcraft players who want to improve by tracking their performance across raid encounters, based on key metrics for their spec.</p>
  <p>It is designed primarily for those who want to improve their basic rotation. It probably will not provide enough information to be useful to advanced players who are already very comfortable with their classes and are now trying to maximize their output.</p>
  <p>This site also will not try to give a detailed overview of each fight's mechanics, as there are multiple other sites designed for that purpose. The goal instead is to distill the logs to a small amount of information about your general execution, which can then be easily tracked and compared across multiple attempts.</p>
  <p>All log information is taken from the <a href="http://www.warcraftlogs.com" target="_blank">Warcraft Logs</a> public API, so you must create a WCL account and upload your logs there first, before importing them to this site.</p>

  <h3>How do I use this site?</h3>
  <p>You can enter a Warcraft Logs report ID to import a log directly, and then request individual encounters to be processed.</p>
  <p>Please note that the log analysis runs on a queue, so it may take a few minutes for this to finish.</p>
  <h4 style="margin-top: 20px">Viewing by character</h4>
  <p>Once you have processed a few logs, you can search for characters by name, and browse all of the fights recorded for that character in one place.</p>
  <p>Multiple reports for the same boss will be shown together, so that you can compare your performance across attempts and see your improvement over time.</p>
  
</div>

app/views/home/announcement.html.erb
<div class="container" style="margin-top: 50px">
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <h3>Ending Active Development</h3>
      <p>This is a hard announcement to make, but I have made the decision to stop actively developing Check My Wow. I want to thank everyone who has supported the site so far and helped me bring it to where it is today. I had a great time working with all of you, and am very proud of what this site has been able to accomplish.</p>

      <p>tl;dr: I love Check My Wow, but you should use <a href="https://wowanalyzer.com">WoW Analyzer</a> because it will improve faster than this site can. 

      <h3>A Brief History</h3>
      <p>Back in Highmaul I was a terrible Brewmaster, but I wanted to get better. I read every resource I could find, compiled a list of the most important things to check for in Warcraft Logs, and would update a spreadsheet every raid night to track my improvement in those areas. This was tedious work and Warcraft Logs had just released an API to access its data, so I started working on a web app that could do the calculations and record-keeping for me. This marked the beginning of Brewmaster Logs, an analysis site exclusively for Brewmasters.</p>
      <p>The site got a little bit of attention, and Babylonius of the Windwalker community contacted me to see if I could develop a similar tool for Windwalkers. The next logical step was to aim to support all classes, and while this was a daunting task I decided to give it a shot. I realized that 80% of the "please check my logs" threads on forums could be answered by checking for simple things like buff uptimes and missed casts, and that most people just weren’t sure what to look for. I imagined that even by checking just a few important points, a tool like this could benefit a great number of people. I registered the checkmywow.com domain in August of 2015, and over the next 2 years it processed nearly 1 million fights.</p>

      <h3>Why End Here?</h3>
      <p>Supporting all 36 specs was already a huge task, but Legion's release made it much more difficult. While previous expansions had largely set rotations aside from certain talents and gear bonuses, Legion introduced artifact traits, legendaries, and interesting talent choices for many specs. These all created more dynamic gameplay (which is a good thing), but made analysis difficult. I simply can't keep up with the amount of detail and nuance that is needed for each spec to make the analysis correct. Check My Wow is certainly still usable for the specs that it supports, but I decided to close this now rather than wait for it to become out of date, because providing wrong information is more harmful than providing no information.</p>

      <h3>Going Forward</h3>
      <p>One factor that makes my decision easier is the emergence of <a href="https://wowanalyzer.com">WoW Analyzer</a>. This is an open-source site with dedicated contributors maintaining each spec, and they have a great community that has been consistently improving the quality of the site's analysis. It really takes a lot of focused attention and effort to do a proper analysis for any of the specs in the game now, and a team of people should be able to do a much better job than I could on my own. I believe that Wow Analyzer will continue to improve and become a better resource, and I want to encourage people to join that community and contribute in whatever way they can.</p>
      <p>Check My Wow will continue to run normally for a while, but I will eventually disable parsing for new fights.</p>

      <h3>Some Last Thoughts</h3>
      <p>I got a lot of help from a lot of people while building this site, and I want to thank all of you again for your invaluable support.</p>
      <p>While I am sad to put an end to this project, I am also very proud of what it has accomplished. When I first launched the site, I don’t think there were other log analysis sites like it. I created it with the belief that an automatic analysis site would be a huge asset to the WoW community, and I think this vision has been realized with tremendous success. Terms like "cast efficiency" are now regularly used in conversation, and there have been more and more targeted analysis sites being made. I'd like to think that Check My Wow played a part in pushing this trend, and I hope it has made a lasting positive impact on the community. I am excited to see how this community and its tools will continue to grow, so that we can all continue to enjoy this great game.</p>
      <p> <3 </p>
      
    </div>
  </div>
</div>

app/views/home/changelog.html.erb
<div class="container" style="margin-top: 50px">
  <h2><%= @spec %> Changelog</h2>
  <% @changelogs.each do |c| %>
    <div class="row">
      <h3><%= c.fp_type %> v<%= c.version %> <small><%= c.created_at.strftime("%D") %></small></h3>
      <div class="col-md-8"><%= raw c.content %></div>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div id="top">
  <div id="splash">
  <%= image_tag('cmw_top.png', size: '15z15') %>
  </div>
  <div id="banner">
      <h3>Import logs</h3>
      <h4>
        <%= form_tag('', method: "get") do %>
          <%= label_tag(:report_id, "Warcraft Logs report ID:") %>
          <%= text_field_tag(:report_id) %>
          <%= submit_tag("Import", class: "btn btn-primary") %>
        <% end %>
        <span style="font-size: 12px">https://www.warcraftlogs.com/reports/<span style="color: rgb(30, 180, 123)">xxxxxxxxxxxxxxxx</span></span>
      </h4>
  </div>
</div>

<div class="container" style="margin-top: 50px;">
  <h3>What is Check My Wow?</h3>
  <p>This site is made for World of Warcraft players who want to improve by tracking their performance across raid encounters, based on key metrics for their spec.</p>
  <p>To get started, please upload your combat logs to <a href="http://www.warcraftlogs.com">Warcraft Logs</a> and enter the report ID above. If it's your first time using Warcraft Logs, please <a href="https://www.warcraftlogs.com/help/start/">see this guide</a> to learn how to get started.</p>
  <p>You can <%= link_to 'read more about the site here', action: 'about' %>.</p>

  <div class="row" style="margin: 50px 0px 50px;">
    <div class="col-md-4">
      <%= image_tag('specific.png', size:'350x200', :style => "border: 3px solid #cccccc; max-width: 100%; height: auto;") %>
      <br /><br />
      <p class="caption">Get class-specific information to analyze your logs</p>
    </div>
    <div class="col-md-4">
      <%= image_tag('compare.png', size:'350x200', :style => "border: 3px solid #cccccc; max-width: 100%; height: auto;") %>
      <br /><br />
      <p class="caption">Track your improvement across fights</p>
    </div>
    <div class="col-md-4">
      <%= image_tag('tank-health.png', size:'350x200', :style => "border: 3px solid #cccccc; max-width: 100%; height: auto;") %>
      <br /><br />
      <p class="caption">See detailed information, like tank health graphs</p>
     </div>
  </div>

  <div class="row" style="border-top: 1px solid #dddddd;">
  <div class="col-md-8">
    <h3 id="news">News</h3>
    <h4>Ending Development <small>09/20</small></h4>
    <p>Check My Wow will no longer be updated. Please <a href="/announcement">click here</a> for the full announcement.</p>
    <h4>Discord channel <small>08/01</small></h4>
    <p>I've created a <a href="https://discord.gg/gd6BbXG" target="_blank">Discord channel</a> that I want to use to communicate changes and updates to the site, since currently it can be hard to notice when your spec's logic has been updated, such as after a large patch. Please feel free to talk about the site, ask questions, or give feedback. If you have questions about how to play your class, your class Discord channels will still be the best place for that.</p>
    <h4>Mythic+ analysis disabled <small>07/11</small></h4>
    <p>Since Mythic+ runs are significantly longer than raid boss pulls, their anlysis was creating too much load for both this site and the Warcraft Logs servers. Unfortunately these will be disabled for the foreseeable future, since the only reasonable solution would be to use much more powerful hardware.</p>
    <br />
    <h4>Parsed fights will be purged after 6 months</h4>
    <p>The site's databases have gotten to be a little too big, and most of the data is from old fights that nobody looks at anymore. I've made some big changes in the site's architecture and will slowly start removing old fight data. Ultimately, all fight data will be kept for 6 months before being deleted. If you ever want to look at old data again, you'll just have to reprocess it.</p>
    <p>I don't have any near term plans for creating paid accounts, but unlimited data retention might be a possible perk if that happens.</p>
    <p>Since there are a lot of changes I made in the background, there might be some issues with existing reports like some players or fights not showing up. If this is the case, clicking on the "Reload from WCL" link on the top of the report's page should solve any issues. Please let me know if something seems to be broken.</p>
  </div>
  <div class="col-md-4">
      <h3 id="changelog">Spec Updates</h3>
      <% @changelogs.each do |changelog| %>
        <p><%= changelog.created_at.strftime("%b %d") %>: <%= link_to("#{changelog.fp_type} v#{changelog.version}", changelog_path(spec: changelog.fp_type)) %></p>
      <% end %>
    </div>
  </div>

  <div class="row" style="border-top: 1px solid #dddddd; margin-top: 25px">
    <div class="col-md-6">
      <h3>Which classes are currently supported?</h3>
      <div class="table-responsive">
        <table class="spec-table">
        <tr class="Deathknight light">
          <td>Death Knight</td>
          <td class="yes">Blood</td>
          <td class="yes">Frost</td>
          <td class="yes">Unholy</td>
        </tr>
        <tr class="Demonhunter light">
          <td>Demon hunter</td>
          <td class="yes">Havoc</td>
          <td class="yes">Vengeance</td>
        </tr>
        <tr class="Druid light">
          <td>Druid</td>
          <td class="yes">Balance</td>
          <td class="yes">Feral</td>
        </tr>
        <tr class="Druid light">
          <td>Druid</td>
          <td class="yes">Guardian</td>
          <td class="yes">Restoration</td>
        </tr>
        <tr class="Hunter light">
          <td>Hunter</td>
          <td class="yes">Beastmastery</td>
          <td class="yes">Marksmanship</td>
          <td class="yes">Survival</td>
        </tr>
        <tr class="Mage light">
          <td>Mage</td>
          <td class="yes">Arcane</td>
          <td class="yes">Fire</td>
          <td class="yes">Frost</td>
        </tr>
        <tr class="Monk light">
          <td>Monk</td>
          <td class="yes">Brewmaster</td>
          <td class="yes">Mistweaver</td>
          <td class="yes">Windwalker</td>
        </tr>
        <tr class="Paladin light">
          <td>Paladin</td>
          <td class="yes">Holy</td>
          <td class="yes">Protection</td>
          <td class="yes">Retribution</td>
        </tr>
        <tr class="Priest light">
          <td>Priest</td>
          <td class="no">Discipline</td>
          <td class="no">Holy</td>
          <td class="yes">Shadow</td>
        </tr>
        <tr class="Rogue light">
          <td>Rogue</td>
          <td class="yes">Assassination</td>
          <td class="yes">Outlaw</td>
          <td class="no">Subtlety</td>
        </tr>
        <tr class="Shaman light">
          <td>Shaman</td>
          <td class="yes">Elemental</td>
          <td class="yes">Enhancement</td>
          <td class="no">Restoration</td>
        </tr>
        <tr class="Warlock light">
          <td>Warlock</td>
          <td class="yes">Affliction</td>
          <td class="no">Demonology</td>
          <td class="yes">Destruction</td>
        </tr>
        <tr class="Warrior light">
          <td>Warrior</td>
          <td class="yes">Arms</td>
          <td class="yes">Fury</td>
          <td class="no">Protection</td>
        </tr>
        </table>
      </div>
    </div>
  </div>
</div>