config/routes.rb
require 'resque/server'
Rails.application.routes.draw do

  root 'home#index'
  get 'logout' => 'home#logout'

  get 'about' => 'home#about'
  get 'announcement' => 'home#announcement'
  get 'changelog' => 'home#changelog'

  resources :players, only: [:show] do
    collection do
      get 'search'
    end
    resources :bosses, only: [] do
      get '/:difficulty' => 'bosses#show', as: :show
      get '/:difficulty/batch_parse' => 'bosses#batch_parse', as: :batch_parse
    end
  end

  resources :guilds, only: [:show] do
    get 'reload'
    collection do
      get 'search'
    end
  end

  resources :reports, only: [:show] do
    get 'status', :defaults => {:format => 'js'}
    get 'reload' => 'reports#reload', as: :reload, :defaults => {:format => 'js'}
    get 'batch/:player_id/' => 'reports#batch', as: :batch
    get 'load_fights/:player_id' => 'reports#load_fights', as: :load_fights, :defaults => { :format => 'js' }
    get 'fight_status/' => 'reports#fight_status', as: :fight_status, :defaults => { :format => 'js' }
    get '/:player_id' => 'reports#show_player', as: :player
    get '/:player_id/:fight_id' => 'fight_parses#show', as: :fight_parse
    get '/:player_id/:fight_id/changelog' => 'fight_parses#changelog', as: :changelog
    get '/:player_id/:fight_id/compare' => 'fight_parses#compare', as: :fp_compare
    get '/:fight_id/:player_id/load_hp_graph' => 'fight_parses#load_hp_graph', as: :load_hp_graph
    get '/:fight_id/:player_id/load_class_graph' => 'fight_parses#load_class_graph', as: :load_class_graph
    get '/:fight_id/:player_id/load_casts_table' => 'fight_parses#load_casts_table', as: :load_casts_table
    get '/:fight_id/:player_id/single_parse' => 'fight_parses#single_parse', as: :single_parse
    get '/:fight_id/:player_id/status' => 'fight_parses#status', as: :fp_status, :defaults => { :format => 'js' }
  end

  resources :zones, only: [:index] do
    collection do 
      get 'refresh'
    end
  end

  if Rails.env.development?
    mount Resque::Server.new, at: "/resque"
  end

  match '*path', via: :all, to: 'home#error_404'

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :fights, primary_key: 'report_id', dependent: :destroy
  has_many :fight_parse_records, primary_key: 'report_id', dependent: :destroy
  has_many :fight_parses, primary_key: 'report_id', dependent: :destroy
  has_many :guild_reports
  has_many :report_players
  has_many :guilds, through: :guild_reports
  has_many :players, through: :report_players
  enum status: [:unprocessed, :processing, :done, :failed, :empty, :queued]

  def fights_for_select
    return Fight.where(report_id: self.report_id).order(:id).map{|f| f.done? ? [f.full_name, f.fight_id] : ["--#{f.full_name}--", nil]}
  end
end

app/views/breadcrumbs/_fight_bosses_dropdown.html.erb
<div id="fight-bosses-dropdown" class="custom-dropdown">
  <%= fight.name %>
  <div id="fight-bosses-dropdown-list" class="list" style="display: none">
    <% bosses.each do |boss| %>
        <% string = "<div class='item'>#{boss[0]} (<small>" %>
        <% string += pluralize(boss[1]['t'], 'Kill') if boss[1]['t'] > 0 %>
        <% string += ', ' if boss[1]['t'] > 0 && boss[1]['f'] > 0 %>
        <% string += pluralize(boss[1]['f'], 'Wipe') if boss[1]['f'] > 0 %>
        <% string = (string + "</small>)</div>").html_safe %>
        <% if player_id.nil? %>
          <%= link_to string, report_fight_path(report.report_id, boss[1]['latest']) %>
        <% else %>
          <%= link_to string, report_fight_parse_path(report.report_id, player_id, boss[1]['latest'], tab: tab) %>
        <% end %>
    <% end %>
  </div>
</div>

<script>
  $("#fight-bosses-dropdown").parent().mouseover(function() {
    $("#fight-bosses-dropdown-list").show();
  });
  $("#fight-bosses-dropdown").parent().mouseout(function() {
    $("#fight-bosses-dropdown-list").hide();
  });
</script>

app/views/breadcrumbs/_fights_dropdown.html.erb
<div id="fights-dropdown" class="custom-dropdown">
  <%= fight.kill_label %>
  <div id="fights-dropdown-list" class="list" style="display: none">
    <% fight_ids = report.fight_parse_records.where(player_id: player_id, boss_id: fight.boss_id).order(:fight_id).pluck(:fight_id) %>
    <% Fight.where(report_id: report.report_id, fight_id: fight_ids).each do |f| %>
      <% if player_id.nil? %>
        <%= link_to "<div class='item #{f.kill? ? 'lgreen' : 'lred' }'>#{f.kill_label}</div>".html_safe, report_fight_path(report.report_id, f.fight_id) %>
      <% else %>
        <%= link_to "<div class='item #{f.kill? ? 'lgreen' : 'lred' }'>#{f.kill_label}</div>".html_safe, report_fight_parse_path(report.report_id, player_id, f.fight_id, tab: tab) %>
      <% end %>
    <% end %>
  </div>
</div>

<script>
  $("#fights-dropdown").parent().mouseover(function() {
    $("#fights-dropdown-list").show();
  });
  $("#fights-dropdown").parent().mouseout(function() {
    $("#fights-dropdown-list").hide();
  });
</script>

app/views/breadcrumbs/_fights_dropdown_with_player.html.erb
<div id="fights-dropdown" class="custom-dropdown">
  <%= fight.full_name %>
  <div id="fights-dropdown-list" class="list" style="display: none">
    <% report.fights.order(:fight_id).each do |f| %>
      <% if f.parsed? %>
        <div class="item">
          <%= link_to f.full_name, report_fight_parse_path(report.report_id, player_id, f.fight_id, tab: tab) %>
        </div>
      <% else %>
        <div class="item disabled"><%= f.name %></div>
      <% end %>
    <% end %>
  </div>
</div>

<script>
  $("#fights-dropdown").parent().mouseover(function() {
    $("#fights-dropdown-list").show();
  });
  $("#fights-dropdown").parent().mouseout(function() {
    $("#fights-dropdown-list").hide();
  });
</script>

app/views/breadcrumbs/_players_dropdown.html.erb
<div id="players-dropdown" class="custom-dropdown">
  <%= Player.player_tag(player_name, player_class, player_spec) %>
  <div id="players-dropdown-list" class="list" style="width: <%=(players.size/10.0).ceil * 150%>px; display: none;">
    <div class="col-sm-<%=(12.0/(players.size/10.0).ceil).ceil%>" style="padding: 0px; border-right: 1px solid #555555">
      <% players.each_with_index do |player, i| %>
        <%= link_to "<div class='item'>#{Player.player_tag(player[1], player[2], player[3])}</div>".html_safe, report_fight_parse_path(report.report_id, player[0], fight_id) %>
        <% if (i + 1) % 10 == 0 %>
          </div>
          <div class="col-sm-<%=(12.0/(players.size/10.0).ceil).ceil%>" style="padding: 0px; border-right: 1px solid #555555">
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<script>
  $("#players-dropdown").parent().mouseover(function() {
    $("#players-dropdown-list").show();
  });
  $("#players-dropdown").parent().mouseout(function() {
    $("#players-dropdown-list").hide();
  });
</script>