config/routes.rb
require 'resque/server'
Rails.application.routes.draw do

  root 'home#index'
  get 'logout' => 'home#logout'

  get 'about' => 'home#about'
  get 'announcement' => 'home#announcement'
  get 'changelog' => 'home#changelog'

  resources :players, only: [:show] do
    collection do
      get 'search'
    end
    resources :bosses, only: [] do
      get '/:difficulty' => 'bosses#show', as: :show
      get '/:difficulty/batch_parse' => 'bosses#batch_parse', as: :batch_parse
    end
  end

  resources :guilds, only: [:show] do
    get 'reload'
    collection do
      get 'search'
    end
  end

  resources :reports, only: [:show] do
    get 'status', :defaults => {:format => 'js'}
    get 'reload' => 'reports#reload', as: :reload, :defaults => {:format => 'js'}
    get 'batch/:player_id/' => 'reports#batch', as: :batch
    get 'load_fights/:player_id' => 'reports#load_fights', as: :load_fights, :defaults => { :format => 'js' }
    get 'fight_status/' => 'reports#fight_status', as: :fight_status, :defaults => { :format => 'js' }
    get '/:player_id' => 'reports#show_player', as: :player
    get '/:player_id/:fight_id' => 'fight_parses#show', as: :fight_parse
    get '/:player_id/:fight_id/changelog' => 'fight_parses#changelog', as: :changelog
    get '/:player_id/:fight_id/compare' => 'fight_parses#compare', as: :fp_compare
    get '/:fight_id/:player_id/load_hp_graph' => 'fight_parses#load_hp_graph', as: :load_hp_graph
    get '/:fight_id/:player_id/load_class_graph' => 'fight_parses#load_class_graph', as: :load_class_graph
    get '/:fight_id/:player_id/load_casts_table' => 'fight_parses#load_casts_table', as: :load_casts_table
    get '/:fight_id/:player_id/single_parse' => 'fight_parses#single_parse', as: :single_parse
    get '/:fight_id/:player_id/status' => 'fight_parses#status', as: :fp_status, :defaults => { :format => 'js' }
  end

  resources :zones, only: [:index] do
    collection do 
      get 'refresh'
    end
  end

  if Rails.env.development?
    mount Resque::Server.new, at: "/resque"
  end

  match '*path', via: :all, to: 'home#error_404'

end

app/models/report.rb
class Report < ActiveRecord::Base
  has_many :fights, primary_key: 'report_id', dependent: :destroy
  has_many :fight_parse_records, primary_key: 'report_id', dependent: :destroy
  has_many :fight_parses, primary_key: 'report_id', dependent: :destroy
  has_many :guild_reports
  has_many :report_players
  has_many :guilds, through: :guild_reports
  has_many :players, through: :report_players
  enum status: [:unprocessed, :processing, :done, :failed, :empty, :queued]

  def fights_for_select
    return Fight.where(report_id: self.report_id).order(:id).map{|f| f.done? ? [f.full_name, f.fight_id] : ["--#{f.full_name}--", nil]}
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :get_report
  protect_from_forgery :except => [:status, :fight_status, :load_fights]

  def show
    @report = Report.find_by(report_id: @report_id)
    if @report.nil?
      begin
        response = HTTParty.get("https://www.warcraftlogs.com:443/v1/report/fights/#{@report_id}?api_key=#{ENV['WCL_API_KEY']}", timeout: 10)
        report_obj = JSON.parse(response.body)
        if !report_obj.has_key? 'fights'
          flash[:danger] = "Report not found (Was given '#{@report_id}' as the report ID)"
          redirect_to :root and return
        end
      rescue
        flash[:danger] = "There was an error performing the request. Please try again at a later time."
        redirect_to :root and return
      end
      begin
        @report = Report.find_or_create_by(report_id: @report_id)
      rescue ActiveRecord::RecordNotUnique
        retry
      end
      @report.queued!
      Resque.enqueue(Parser, @report_id)
    elsif @report.unprocessed?
      @report.queued!
      Resque.enqueue(Parser, @report_id)
    end
    player_ids = FightParseRecord.where(report_id: @report_id).order(:class_type).pluck(:player_id).uniq
    if player_ids.blank? and @report.done?
      redirect_to report_reload_path(report_id: @report_id) and return
    end
    @player_id = player_ids.include?(params[:player_id].to_i) ? params[:player_id].to_i : player_ids.first
    @players = Player.where(player_id: player_ids).order(:class_type).pluck(:player_id, :player_name, :class_type)
    @fight_list = {}
    FightParseRecord.where(report_id: @report_id, player_id: @player_id).includes(:fight).order(fight_id: :asc).each do |fpr|
      fight = fpr.fight
      next if fight.nil?
      @fight_list[fight.boss_id.to_s + fight.difficulty.to_s] ||= {name: "#{DifficultyType.label(fight.difficulty)} #{fight.name}", kills: [], wipes: []}
      fight.kill? ? @fight_list[fight.boss_id.to_s + fight.difficulty.to_s][:kills] << fpr : @fight_list[fight.boss_id.to_s + fight.difficulty.to_s][:wipes] << fpr
    end
    @boss_id = @fight_list.has_key?(params[:boss_id].to_i) ? params[:boss_id].to_i : @fight_list.keys.first
    @fp_ids = Hash[FightParseRecord.where(report_id: @report_id, status: [FightParseRecord.statuses[:queued], FightParseRecord.statuses[:processing]]).order(:class_type, :spec).map{|fp| [fp.id, fp]}]
    @progresses = Hash[Progress.where(model_type: 'FightParse', model_id: @fp_ids.map{|fp|fp[0]}).to_a.map{|p|[p.model_id, p]}]
    @queued = @fp_ids.reject{|id, fp| !fp.queued? }.size
    @processing = @fp_ids.reject{|id, fp| !fp.processing? }.size
  end

  def reload
    @report = Report.find_by(report_id: @report_id)
    if @report.nil?
      redirect_to :show and return
    end
    begin
      response = HTTParty.get("https://www.warcraftlogs.com:443/v1/report/fights/#{@report_id}?api_key=#{ENV['WCL_API_KEY']}", timeout: 10)
      report_obj = JSON.parse(response.body)
      if !report_obj.has_key? 'fights'
        flash[:danger] = "Report not found (Was given '#{@report_id}' as the report ID)"
        redirect_to :root and return
      end
    rescue
      flash[:danger] = "There was an error performing the request. Please try again at a later time."
      redirect_to :root and return
    end
    unless @report.queued? || @report.processing?
      @report.queued!
      Resque.enqueue(Parser, @report_id)
    end
    
    redirect_to report_path(@report_id) and return

    respond_to do |format|
      format.js
    end
  end

  def show_player
    @player_id = params[:player_id]   

    fight = FightParseRecord.where(report_id: @report_id, player_id: @player_id).order(:fight_id).first
    if fight.nil?
      flash[:danger] = "Player not found"
        redirect_to :root and return
    end
    @fight_id = fight.fight_id
    redirect_to report_fight_parse_path(@report_id, @player_id, @fight_id) and return
  end

  def status
    @report = Report.find_by(report_id: @report_id)
    @progress = Progress.find_by(model_type: 'Report', model_id: @report_id)
    respond_to do |format|
      format.js
    end
  end

  def fight_status
    @report = Report.find_by(report_id: @report_id)
    @fp_ids = Hash[FightParseRecord.where(report_id: @report_id, status: [FightParseRecord.statuses[:queued], FightParseRecord.statuses[:processing]]).order(:class_type, :spec).map{|fpr| [fpr.id, fpr]}]
    fp_ids = params[:fp_ids].to_s.split('.')
    @fp_ids.merge! Hash[FightParseRecord.where(id: fp_ids).map{|fpr| [fpr.id, fpr]}]
    @progresses = Hash[Progress.where(model_type: 'FightParse', model_id: @fp_ids.keys).to_a.map{|p|[p.model_id, p]}]
    @queued = @fp_ids.reject{|id, fpr| !fpr.queued? }.size
    @processing = @fp_ids.reject{|id, fpr| !fpr.processing? }.size
    
    respond_to do |format|
      # format.html { redirect_to report_path(id: @report_id) and return }
      format.js
    end
  end

  def load_fights
    @report = Report.find_by(report_id: @report_id)
    @player_id = params[:player_id]
    @fight_list = {}
    FightParseRecord.where(report_id: @report_id, player_id: @player_id).includes(:fight).order(fight_id: :asc).each do |fp|
      @fight_list[fp.fight.boss_id.to_s + fp.fight.difficulty.to_s] ||= {name: "#{DifficultyType.label(fp.fight.difficulty)} #{fp.fight.name}", kills: [], wipes: []}
      fp.fight.kill? ? @fight_list[fp.fight.boss_id.to_s + fp.fight.difficulty.to_s][:kills] << fp : @fight_list[fp.fight.boss_id.to_s + fp.fight.difficulty.to_s][:wipes] << fp
    end
    @boss_id = @fight_list.has_key?(params[:boss_id].to_i) ? params[:boss_id].to_i : @fight_list.keys.first

    respond_to do |format|
      # format.html { redirect_to report_path(id: @report_id, player_id: @player_id) and return }
      format.js
    end
  end

  def batch
    @player_id = params[:player_id]
    @player = Player.find_by(player_id: @player_id)
    @report_id = params[:report_id]
    search_params = {player_id: @player_id, report_id: @report_id}
    search_params[:kill] = true if params[:kills]
    @fprs = FightParseRecord.where(search_params).to_a
    @fprs.each do |fpr|
      fpr.enqueue
    end
    redirect_to report_path(id: @report_id, player_id: @player_id) and return
  end

  private

  def get_report
    @report_id = (params[:report_id] || params[:id]).gsub(/[^0-9A-Za-z.\-]/, '?')
  end
end

app/views/reports/_button.html.erb
<% report ||= locals[:report] %>
<% case locals[:force] || report.status %>
  <% when 'unprocessed' %>
    <%= link_to('Process Report', report_path(report.report_id), class: 'btn btn-default') %>
  <% when 'processing' %>
    <%= link_to('Processing...', report_path(report.report_id), class: 'btn btn-warning', waiting: true) %>
  <% when 'queued' %>
    <%= link_to('Queued...', report_path(report.report_id), class: 'btn btn-default', waiting: true) %>
  <% when 'done' %>
    <%= link_to('View Report', report_path(report.report_id), class: 'btn btn-success') %>
  <% when 'empty' %>
    <%= link_to('No data found', '#', class: 'btn btn-error', disabled: 'disabled') %>
  <% else %>
    <%= link_to('Failed :(', '#', class: 'btn btn-error', disabled: 'disabled') %>
  <% end %>

app/views/reports/_content_div.html.erb
<div id="report-progress" style="display:<%=@processing + @queued > 0 ? 'block' : 'none'%>">
  <div id="progress-content">
    <%= render 'reports/progress_div' %>
  </div>
  <div id="progress-popover">
    <%= render 'reports/progress_popover' %>
  </div>
</div>

<div class="left" id="player-list">
  <% @players.each_with_index do |player, i| %>
    <%= link_to Player.player_tag(player[1], player[2], nil, false), report_load_fights_path(@report.report_id, player[0]), class: "left player row-block click #{player[2]} #{player[0] == @player_id ? 'active dark' : 'text'}", remote: true %>
    <% if (i + 1) % 2 == 0 %>
      <br />
    <% end %>
  <% end %>
</div>
<% if @players.blank? %>
  <p>No fights were found in this report. Please check to see if there is anything wrong with the uploaded log file.</p>
  <br />
  <h4>Can you view you report on Warcraft Logs?</h4>
  <p>Sometimes a combat log file can become corrupted, and have missing or incorrect data.</p>
  <br />
  <h4>Is your log on Warcraft Logs set to private?</h4>
  <p>Check My Wow uses public APIs to access your data, so it cannot collect information from private logs.</p>
  <br />
  <h4>Do you have advanced combat logging enabled?</h4>
  <p>Without advanced combat logging, certain key information like player specs and talents are not recorded.<p>
  <p>You can enabled this setting within World of Warcraft, in the Network pane under System preferences.</p>
  <br />
  <h4>Did you log this report before the latest content patch?</h4>
  <p>Please note that old reports from before patch 7.0 will not be displayed.</p>
<% else %>
  <div class="left" id="fight-list" style="margin-left: 20px;">
    <%= render 'reports/fight_list' %>
  </div>
<% end %>
<script>
  var checkTimeout = null;
  $(function(){
    $(".player.row-block").hover(function() {
      if (!$(this).hasClass('active')) {
        $(this).toggleClass('text');
        $(this).toggleClass('dark');
      }
    })
    $(".player.row-block").click(function() {
      if (!$(this).hasClass('active')) {
        $('.player.active').addClass('text');
        $('.player.active').removeClass('dark');
        $('.player.active').removeClass('active');
        $(this).addClass('active');
        $(this).addClass('dark');
        $(this).removeClass('text');
      }
    })
  });
</script>

app/views/reports/_fight_list.html.erb
<% unless @fight_list.nil? %>
  <div class="left">
    <%= link_to "Process all Kills", report_batch_path(@report_id, @player_id, {kills: true}), {class: "boss row-block large"} %>
    <%= link_to "Process all Fights", report_batch_path(@report_id, @player_id), {class: "boss row-block large spacer"} %>
    <% @fight_list.each do |boss_id, boss| %>
    <a val="<%=boss_id%>" class="boss row-block click large <%=boss_id == @boss_id ? 'active highlight' : ''%>">
      <%="#{boss[:name]} (#{pluralize(boss[:kills].size, 'kill')}#{boss[:wipes].size > 0 ? ', ' + pluralize(boss[:wipes].size, 'wipe') : ''})".html_safe %>
    </a>
    <% end %>
  </div>
  <% @fight_list.each do |boss_id, boss| %>
    <div id="fps-<%=boss_id%>" class="left" style="display: <%=boss_id == @boss_id ? 'block' : 'none'%>">
      <% (boss[:kills] + boss[:wipes]).each do |fp, kill| %>
        <% next if fp.class_type.nil? %>
        <div class="row-block large" style="margin-left: 20px;">
          <div class="left">
            <%= image_tag("class/#{fp.class_type.downcase}#{fp.spec.blank? ? "" : "/#{fp.spec.downcase}"}.jpg", size: '21x21', class: 'icon') %>&nbsp;&nbsp;
            <%= fp.fight.kill? ? "Kill" : "Wipe - #{fp.fight.boss_percent.to_i / 100}%" %> <%= fp.fight.fight_time_s %>
          </div>
          <div id="fp-<%=fp.id%>" class="right">
            <%= render 'fight_parses/shared/button', locals: {fp: fp} %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
<% end %>
<script>
  $(function() {
    $(".boss.row-block").hover(function() {
      if (!$(this).hasClass('active')) {
        $(this).toggleClass('highlight');
      }
    })
    $(".boss.row-block").click(function() {
      if (!$(this).hasClass('active')) {
        $('.boss.active').removeClass('highlight');
        $('#fps-'+$($('.boss.active')[0]).attr('val')).hide();
        $('.boss.active').removeClass('active');
        $(this).addClass('active');
        $('#fps-'+$(this).attr('val')).show();
      }
    })
  });
  
</script>

app/views/reports/_fightparse_list.html.erb
<% fight_parses ||= locals[:fight_parses] %>
<% fight_parses.each do |fp| %>
  <div class="row-block large" style="margin-left: 20px;">
    <div class="left">
      <%= image_tag("class/#{fp.class_type.downcase}#{fp.spec.blank? ? "" : "/#{fp.spec.downcase}"}.jpg", size: '21x21', class: 'icon') %>&nbsp;&nbsp;
      <%= fp.kill? ? 'Kill' : 'Wipe' %> <%= fp.fight_time_s %>
    </div>
    <div class="right">
      <%= render 'fight_parses/shared/button', locals: {fp: fp} %>
    </div>
  </div>
<% end %>

app/views/reports/_progress_div.html.erb
<%= pluralize(@queued, 'fight') %> queued, <%= pluralize(@processing, 'fight') %> processing
&nbsp;<small><small>(Last updated <%= local_time(Time.now, "%l:%M:%S") %>)</small></small>
&nbsp;&nbsp;&nbsp;<small><a onclick="$('#progress-popover').toggle();">See details</a></small>
<script>
  function checkStatus(fp_id = null) {
    if (fp_id == null) {
      $.ajax({
        url: '<%= report_fight_status_path(@report_id, fp_ids: @fp_ids.keys.join(".")) %>',
        cache: false
      });
    } else {
      $.ajax({
        url: '<%= report_fight_status_path(@report_id, fp_ids: @fp_ids.keys.join('.')) %>'+'.'+fp_id,
        cache: false
      });
    }
  }
  var checkTimeout;
  if (checkTimeout != null) clearTimeout(checkTimeout);
  <% if @processing + @queued > 0 %>
    checkTimeout = setTimeout(checkStatus, 3000);
  <% end %>
</script>

app/views/reports/_progress_popover.html.erb
<table>
  <% @fp_ids.each do |id, fpr| %>
    <tr id="fp-progress-<%=id%>">
      <td><%= Player.player_tag(fpr.player_name, fpr.class_type, fpr.spec, false) %></td>
      <td><%= fpr.fight.name %> <%= "(#{fpr.fight.boss_percent.to_i / 100}%)" unless fpr.fight.kill? %></td>
      <td class="status" data-status="<%=fpr.status%>"><%= fpr.status.capitalize %></td>
      <td>
        <% if fpr.processing? %>
          <div class="progress">
            <% if !@progresses[fpr.id.to_s].nil? %>
              <div class="progress-bar progress-bar-success" role="progressbar" style="width: <%= 100 * @progresses[fpr.id.to_s].current / @progresses[fpr.id.to_s].finish rescue 0 %>%"></div>
            <% end %>
          </div>
        <% elsif fpr.done? %>
          <%= link_to('View Report', report_fight_parse_path(fpr.report_id, fpr.player_id, fpr.fight_id)) %>
        <% else %>
          <div style="width: 100px"></div>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/reports/_waiting.html.erb
<% if @report.queued? %>
  <p>This report is currently in the queue to be processed. This page will automatically reload once there has been an update.</p>
  <br />
  <p>Current queue size: <%= pluralize Resque.size(:parse) + Resque.size(:single_parse) + Resque.working.size, 'report' %></p>
  <br />
  <p><small>Last updated: <%= local_time(Time.now, "%l:%M:%S") %></small></p>
<% elsif @report.processing? %>
  <p>This report is currently being imported.</p>
  <%= render 'shared/progress' %>
  <br />
  <p><small>Last updated: <%= local_time(Time.now, "%l:%M:%S") %></small></p>
<% end %>
<input type="hidden" id="report-status" value="<%=@report.status%>" />
<script>
  function checkReportStatus() {
    $.ajax({
      url: '<%= report_status_path(@report_id) %>',
      cache: false
    });
  }
  <% if !@report.done? %>
    var checkTimeout = setTimeout(checkReportStatus, 3000);
  <% end %>
</script>

app/views/reports/fight_status.js.erb
<% if @processing + @queued > 0 %>
  $("#report-progress").show();
<% end %>

$('#progress-content').html("<%= escape_javascript(render 'reports/progress_div').html_safe %>");
$('#progress-popover').html("<%= escape_javascript(render 'reports/progress_popover').html_safe %>");
<% @fp_ids.each do |id, fp| %>
  $('#fp-<%=id%>').html("<%= escape_javascript(render 'fight_parses/shared/button', locals: {fp: fp}).html_safe %>")
<% end %>

app/views/reports/load_fightparses.js.erb
$('#fightparse-list').html("<%= escape_javascript(render(:partial => 'reports/fightparse_list', locals: {fight_parses: @fight_parses})).html_safe %>");

app/views/reports/load_fights.js.erb
$('#fight-list').html("<%= escape_javascript(render(:partial => 'reports/fight_list')).html_safe %>");
init_bosses();

app/views/reports/show.html.erb
<% breadcrumb :report, @report, true %>
<% provide(:title, @report.title) %>
<div class="container">
  <% if @report.done? %>
    <div id="report-div"><%= render 'reports/content_div' %></div>
  <% elsif @report.failed? %>
    <p>An error has occured while processing this report. The dev has been notified of this, and will look into it as soon as possible.</p>
  <% elsif @report.blank? %>
    <p>No fights were found in this report.</p>
    <p>It's also possible that this is a private report, in which case the API can't retrieve fight information.</p>
  <% else %>
    <div id="report-div"><%= render 'reports/waiting' %></div>
  <% end %>
</div>

app/views/reports/status.js.erb
<% if @report.done? %>
  location.reload();
<% else %>
  $('#report-div').html("<%= escape_javascript(render(:partial => 'reports/waiting')).html_safe %>");
<% end %>